# Generated by Django 5.2.14 on 2026-05-15 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='nome do projeto ou iniciativa')),
                ('tipo_solicitacao', models.CharField(choices=[('reuniao_inicial', 'Reunião inicial'), ('uso_infraestrutura', 'Uso da infraestrutura multiusuária'), ('apoio_tecnico', 'Apoio técnico em interoperabilidade ou governança de dados'), ('validacao_tecnica', 'Validação técnica de solução digital'), ('cooperacao_cientifica', 'Cooperação científica ou projeto de pesquisa'), ('projeto_institucional', 'Projeto institucional com secretaria ou serviço de saúde'), ('outro', 'Outro')], max_length=64, verbose_name='tipo de solicitação')),
                ('infraestrutura', models.CharField(max_length=255, verbose_name='infraestrutura desejada')),
                ('instituicao_nome', models.CharField(max_length=255, verbose_name='nome da instituição')),
                ('perfil_instituicao', models.CharField(choices=[('secretaria_estadual', 'Secretaria estadual de saúde'), ('secretaria_municipal', 'Secretaria municipal de saúde'), ('servico_publico', 'Serviço de saúde público'), ('servico_privado_filantropico', 'Serviço de saúde privado ou filantrópico'), ('pesquisa_pos', 'Programa de pós-graduação / grupo de pesquisa'), ('empresa_startup', 'Empresa / startup / healthtech'), ('terceiro_setor', 'Organização do terceiro setor'), ('outro', 'Outro')], max_length=64, verbose_name='perfil da instituição solicitante')),
                ('objetivos_solicitacao', models.JSONField(default=list, verbose_name='objetivos da solicitação')),
                ('demanda_descricao', models.TextField(verbose_name='descrição da demanda')),
                ('dados_sistemas_envolvidos', models.CharField(choices=[('sim_identificados', 'Sim, já existem dados/sistemas identificados'), ('sim_mapear', 'Sim, mas ainda precisamos mapear'), ('nao_orientacao', 'Não, é uma demanda inicial de orientação'), ('nao_sei', 'Não sei informar')], max_length=64, verbose_name='dados clínicos ou sistemas envolvidos')),
                ('detalhes_tecnicos', models.TextField(blank=True, verbose_name='detalhes técnicos adicionais')),
                ('prazo_urgencia', models.CharField(choices=[('conversa_inicial', 'Apenas conversa inicial'), ('30_dias', 'Próximos 30 dias'), ('1_3_meses', '1 a 3 meses'), ('3_6_meses', '3 a 6 meses'), ('sem_prazo', 'Sem prazo definido')], max_length=32, verbose_name='prazo ou urgência')),
                ('data_inicio', models.DateField(verbose_name='data início')),
                ('data_fim', models.DateField(verbose_name='data fim')),
                ('responsavel_nome', models.CharField(max_length=255, verbose_name='nome do responsável')),
                ('responsavel_email', models.EmailField(db_index=True, max_length=254, verbose_name='email do responsável')),
                ('concorda_lgpd', models.BooleanField(verbose_name='concorda com LGPD')),
                ('concorda_etica', models.BooleanField(verbose_name='concorda com uso ético')),
                ('status', models.CharField(choices=[('em_analise', 'Em análise'), ('aprovado', 'Aprovado'), ('em_execucao', 'Em execução'), ('finalizado', 'Finalizado'), ('rejeitado', 'Rejeitado')], db_index=True, default='em_analise', max_length=32, verbose_name='status')),
                ('notas_admin', models.TextField(blank=True, verbose_name='notas administrativas')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data de envio')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitação de acesso',
                'verbose_name_plural': 'solicitações de acesso',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='access_requ_status_b2dc4f_idx'), models.Index(fields=['responsavel_email', '-created_at'], name='access_requ_respons_fa93ec_idx')],
            },
        ),
    ]
